name: Build and Push Docker Compose Images

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build images with Docker Compose
      run: docker compose build

    - name: Debug - Show all images
      run: |
        echo "=== All Docker images ==="
        docker images --all
        echo "=== Docker Compose services ==="
        docker compose config --services

    - name: Tag and push images
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
        
        # Get services defined in docker-compose.yml
        services=$(docker compose config --services)

        i=1
        for service in $services; do
          # Get the image ID for each service
          image_id=$(docker images --filter "reference=*${service}*" --format "{{.ID}}" | head -n 1)

          if [ -n "$image_id" ]; then
            echo "Tagging $service with image $image_id"

            docker tag $image_id $USERNAME/class32-resturant-app-microservices-$service:$SHORT_SHA
            docker tag $image_id $USERNAME/class32-resturant-app-microservices-$service:latest

            docker push $USERNAME/class32-resturant-app-microservices-$service:$SHORT_SHA
            docker push $USERNAME/class32-resturant-app-microservices-$service:latest
          else
            echo "⚠️ Warning: No image found for $service"
          fi

          i=$((i+1))
        done
